### ISSUE TITLE
Amend vulgar bit of the README?

### ISSUE THREAD

**Issue by habnabit** [KOLANICH-libs/Pipeline.py#1]
>`Python 2` is dead, stop raping its corpse.

It's a bit sensationalist, but also remarkably vulgar. Is this really necessary?

**Comment by KOLANICH** [comment]
Yes, it's really necessary, I think python 2 needs some coup de grace. And the most importantly, 'stop raping something's corpse' in Russian [is a well-known jargon phrase which is often used to speak about obsolete technologies](https://lurkmore.to/%D0%9D%D0%B0%D1%81%D0%B8%D0%BB%D0%BE%D0%B2%D0%B0%D1%82%D1%8C_%D1%82%D1%80%D1%83%D0%BF).

**Comment by habnabit** [comment]
The connotations in English are a bit different. I urge you to reconsider. 🙂

**Comment by habnabit** [comment]
I just looked at this issue again, and I don't think they generate notifications, so I just wanted to note that there's 7 👍  right now.
